Add i386 support
It is now possible to use x86-64 and i386 for testing purpose. The
i386 is going to be used to test the U-Boot backend.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

diff --git a/scripts/updatehub-qemu b/scripts/updatehub-qemu
--- a/scripts/updatehub-qemu
+++ b/scripts/updatehub-qemu
@@ -9,18 +9,38 @@
 
 set -e
 
-IMAGE=$1
-MAC=$2
+ARCH=$1
+IMAGE=$2
+MAC=$3
 
 [ -n "$MAC" ] || MAC="52:54:00$(od -txC -An -N3 /dev/urandom|tr \  :)"
 
 export QEMU_AUDIO_DRV=none
 
-exec qemu-system-x86_64 \
-    -cpu qemu64,+ssse3 \
-    -m 128M \
-	-drive if=pflash,readonly,file=/usr/share/ovmf/bios.bin \
-	-drive if=virtio,format=raw,file=${IMAGE} \
-    -net nic,macaddr=${MAC} \
-    -net user,hostfwd=tcp::22-:22 \
-	-nographic
+case "${ARCH}" in
+    i386)
+    exec qemu-system-i386 \
+         -M pc \
+         -m 128M \
+         -drive if=pflash,format=raw,readonly,file=/usr/share/ovmf/ovmf_code_ia32.bin \
+         -drive if=ide,format=raw,file=${IMAGE} \
+         -net nic,macaddr=${MAC} \
+         -net user,hostfwd=tcp::22-:22 \
+         -nographic
+    ;;
+    x86-64)
+    exec qemu-system-x86_64 \
+         -cpu qemu64,+ssse3 \
+         -m 128M \
+         -drive if=pflash,format=raw,readonly,file=/usr/share/ovmf/ovmf_code_x64.bin \
+         -drive if=pflash,format=raw,file=/usr/share/ovmf/ovmf_vars_x64.bin \
+         -drive if=virtio,format=raw,file=${IMAGE} \
+         -net nic,macaddr=${MAC} \
+         -net user,hostfwd=tcp::22-:22 \
+         -nographic
+    ;;
+    *)
+    echo "ERROR: Unknown ARCH value. Valid ones are: i386 or x86-64"
+    exit 1
+    ;;
+esac
